### ISSUE TITLE
Lacking functionality

### ISSUE THREAD

**Issue by W-orko** [smellslikekeenspirit/Scrapeit#1]
Script seems to lack privacy functionality, developer's agent ID is visible

**Comment by smellslikekeenspirit** [comment]
I have added any and all functionality, that was just a result of procrastination. Thanks for the notice.  
(Edit: I'm afraid the API credentials are necessary for the script to run, and I should encrypt them but I have exams)

**Comment by 0xInfection** [comment]
Why not double b64 them and use a function to decode it a.k.a. encrypt them? At least will save the credentials from being scraped by online scrapers. :D
